export type Career = {
  id: string;
  name: string;
  nameHT: string;
  domain: string;
  riasecCodes: string[];
  description: string;
  subjects: string[];
  skills: string[];
  salary: string;
  outlook: string;
};

export type University = {
  id: string;
  name: string;
  country: string;
  city: string;
  type: string;
  languages: string[];
  website: string;
  programs: Program[];
};

export type Program = {
  id: string;
  name: string;
  nameHT: string;
  domain: string;
  duration: string;
  level: string;
  language: string;
  tuitionMin: number;
  tuitionMax: number;
  currency: string;
  deadline: string;
  scholarship: boolean;
  requirements: string[];
  universityId: string;
  universityName: string;
  country: string;
};

export type Mentor = {
  id: string;
  name: string;
  profession: string;
  domain: string;
  bio: string;
  languages: string[];
  country: string;
  availability: string;
  sessions: number;
  rating: number;
  avatar: string;
};

export type RoadmapStep = {
  grade: string;
  actions: string[];
};

export type CareerRoadmap = {
  careerId: string;
  steps: RoadmapStep[];
  documents: string[];
};

export const CAREERS: Career[] = [
  {
    id: "medecine",
    name: "Médecine",
    nameHT: "Medsin",
    domain: "Santé",
    riasecCodes: ["I", "S"],
    description: "Diagnostiquer et traiter les maladies humaines.",
    subjects: ["Biologie", "Chimie", "Physique", "Mathématiques"],
    skills: ["Empathie", "Rigueur", "Communication", "Résolution de problèmes"],
    salary: "$800-3000/mois",
    outlook: "Très haute demande en Haïti",
  },
  {
    id: "informatique",
    name: "Informatique / Génie Logiciel",
    nameHT: "Enfòmatik",
    domain: "Technologie",
    riasecCodes: ["I", "R"],
    description: "Concevoir et développer des logiciels et systèmes informatiques.",
    subjects: ["Mathématiques", "Physique", "Logique"],
    skills: ["Programmation", "Analyse", "Créativité", "Travail en équipe"],
    salary: "$600-5000/mois",
    outlook: "Secteur en forte croissance mondiale",
  },
  {
    id: "gestion",
    name: "Gestion / Administration des affaires",
    nameHT: "Jesyon Biznis",
    domain: "Commerce",
    riasecCodes: ["E", "C"],
    description: "Gérer des organisations, des projets et des ressources humaines.",
    subjects: ["Économie", "Mathématiques", "Comptabilité"],
    skills: ["Leadership", "Communication", "Organisation", "Négociation"],
    salary: "$500-3000/mois",
    outlook: "Forte demande dans le secteur privé haïtien",
  },
  {
    id: "droit",
    name: "Droit",
    nameHT: "Dwa",
    domain: "Juridique",
    riasecCodes: ["E", "S"],
    description: "Conseiller, représenter et défendre les droits des individus et organisations.",
    subjects: ["Histoire", "Français", "Philosophie", "Sociologie"],
    skills: ["Argumentation", "Recherche", "Rédaction", "Éloquence"],
    salary: "$600-4000/mois",
    outlook: "Stable, spécialités en droit des affaires très demandées",
  },
  {
    id: "architecture",
    name: "Architecture & Génie Civil",
    nameHT: "Achitekti & Jeni Sivil",
    domain: "Ingénierie",
    riasecCodes: ["R", "A", "I"],
    description: "Concevoir et construire des bâtiments et infrastructures.",
    subjects: ["Mathématiques", "Physique", "Dessin technique"],
    skills: ["Créativité", "Précision", "Gestion de projet", "Vision spatiale"],
    salary: "$700-4000/mois",
    outlook: "Haute demande post-reconstruction en Haïti",
  },
  {
    id: "education",
    name: "Sciences de l'Éducation",
    nameHT: "Syans Edikasyon",
    domain: "Éducation",
    riasecCodes: ["S", "A"],
    description: "Former et éduquer les générations futures.",
    subjects: ["Psychologie", "Philosophie", "Sociologie", "Français"],
    skills: ["Patience", "Communication", "Pédagogie", "Empathie"],
    salary: "$300-1500/mois",
    outlook: "Pilier du développement national",
  },
  {
    id: "agronomie",
    name: "Agronomie / Agriculture",
    nameHT: "Agwonomi",
    domain: "Agriculture",
    riasecCodes: ["R", "I"],
    description: "Améliorer les techniques agricoles et la sécurité alimentaire.",
    subjects: ["Biologie", "Chimie", "Sciences naturelles"],
    skills: ["Analyse", "Terrain", "Innovation", "Durabilité"],
    salary: "$400-2000/mois",
    outlook: "Secteur stratégique pour Haïti",
  },
  {
    id: "communication",
    name: "Communication / Journalisme",
    nameHT: "Kominikasyon",
    domain: "Médias",
    riasecCodes: ["A", "E", "S"],
    description: "Informer, analyser et diffuser des contenus médiatiques.",
    subjects: ["Français", "Histoire", "Sociologie"],
    skills: ["Rédaction", "Investigation", "Expression orale", "Numérique"],
    salary: "$300-2000/mois",
    outlook: "Évolution vers le digital",
  },
];

export const UNIVERSITIES: University[] = [
  {
    id: "ueh",
    name: "Université d'État d'Haïti (UEH)",
    country: "Haïti",
    city: "Port-au-Prince",
    type: "Public",
    languages: ["Français", "Créole"],
    website: "https://ueh.edu.ht",
    programs: [],
  },
  {
    id: "quisqueya",
    name: "Université Quisqueya",
    country: "Haïti",
    city: "Port-au-Prince",
    type: "Privé",
    languages: ["Français", "Anglais"],
    website: "https://uniq.edu.ht",
    programs: [],
  },
  {
    id: "notre-dame",
    name: "Université Notre-Dame d'Haïti",
    country: "Haïti",
    city: "Port-au-Prince",
    type: "Privé",
    languages: ["Français"],
    website: "https://undh.edu.ht",
    programs: [],
  },
  {
    id: "uag",
    name: "Université des Antilles (Guadeloupe)",
    country: "France",
    city: "Pointe-à-Pitre",
    type: "Public",
    languages: ["Français"],
    website: "https://univ-antilles.fr",
    programs: [],
  },
  {
    id: "uqam",
    name: "Université du Québec à Montréal (UQAM)",
    country: "Canada",
    city: "Montréal",
    type: "Public",
    languages: ["Français"],
    website: "https://uqam.ca",
    programs: [],
  },
];

export const PROGRAMS: Program[] = [
  {
    id: "ueh-med",
    name: "Doctorat en Médecine",
    nameHT: "Doktora Medsin",
    domain: "Santé",
    duration: "7 ans",
    level: "Doctorat",
    language: "Français",
    tuitionMin: 0,
    tuitionMax: 500,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Bac scientifique", "Concours d'entrée", "Certificat médical"],
    universityId: "ueh",
    universityName: "Université d'État d'Haïti (UEH)",
    country: "Haïti",
  },
  {
    id: "ueh-droit",
    name: "Licence en Droit",
    nameHT: "Lisans Dwa",
    domain: "Juridique",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 0,
    tuitionMax: 300,
    currency: "USD/an",
    deadline: "Septembre",
    scholarship: true,
    requirements: ["Bac", "Dossier scolaire"],
    universityId: "ueh",
    universityName: "Université d'État d'Haïti (UEH)",
    country: "Haïti",
  },
  {
    id: "quisqueya-info",
    name: "Licence en Informatique",
    nameHT: "Lisans Enfòmatik",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 2000,
    tuitionMax: 3500,
    currency: "USD/an",
    deadline: "Août",
    scholarship: false,
    requirements: ["Bac", "Test de niveau", "Lettre de motivation"],
    universityId: "quisqueya",
    universityName: "Université Quisqueya",
    country: "Haïti",
  },
  {
    id: "quisqueya-gestion",
    name: "Licence en Gestion des Affaires",
    nameHT: "Lisans Jesyon Biznis",
    domain: "Commerce",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 2000,
    tuitionMax: 3500,
    currency: "USD/an",
    deadline: "Août",
    scholarship: false,
    requirements: ["Bac", "Dossier scolaire"],
    universityId: "quisqueya",
    universityName: "Université Quisqueya",
    country: "Haïti",
  },
  {
    id: "notre-dame-edu",
    name: "Licence en Sciences de l'Éducation",
    nameHT: "Lisans Syans Edikasyon",
    domain: "Éducation",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 1500,
    tuitionMax: 2500,
    currency: "USD/an",
    deadline: "Septembre",
    scholarship: true,
    requirements: ["Bac", "Lettre de motivation", "Références"],
    universityId: "notre-dame",
    universityName: "Université Notre-Dame d'Haïti",
    country: "Haïti",
  },
  {
    id: "uag-droit",
    name: "Licence en Droit",
    nameHT: "Lisans Dwa (Frans)",
    domain: "Juridique",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 3000,
    tuitionMax: 5000,
    currency: "USD/an",
    deadline: "Mai",
    scholarship: true,
    requirements: ["Bac français équivalent", "Parcoursup", "Niveau B2 français"],
    universityId: "uag",
    universityName: "Université des Antilles",
    country: "France",
  },
  {
    id: "uqam-info",
    name: "Baccalauréat en Informatique",
    nameHT: "Bakaloreya Enfòmatik (Kanada)",
    domain: "Technologie",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 6000,
    tuitionMax: 10000,
    currency: "USD/an",
    deadline: "Février",
    scholarship: true,
    requirements: ["Diplôme secondaire", "Test de français", "Relevés de notes"],
    universityId: "uqam",
    universityName: "Université du Québec à Montréal",
    country: "Canada",
  },
  {
    id: "ueh-agro",
    name: "Licence en Agronomie",
    nameHT: "Lisans Agwonomi",
    domain: "Agriculture",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 0,
    tuitionMax: 400,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Bac scientifique", "Concours d'entrée"],
    universityId: "ueh",
    universityName: "Université d'État d'Haïti (UEH)",
    country: "Haïti",
  },
];

export const MENTORS: Mentor[] = [
  {
    id: "m1",
    name: "Dr. Marie-Claire Desrosiers",
    profession: "Médecin Pédiatre",
    domain: "Santé",
    bio: "Médecin avec 15 ans d'expérience en pédiatrie. Ancienne résidente à l'Hôpital de l'Université d'État d'Haïti. Passionnée par la formation de la prochaine génération de médecins haïtiens.",
    languages: ["Français", "Créole", "Anglais"],
    country: "Haïti",
    availability: "Week-ends",
    sessions: 48,
    rating: 4.9,
    avatar: "MC",
  },
  {
    id: "m2",
    name: "Jean-Baptiste Pierre",
    profession: "Ingénieur Logiciel Senior",
    domain: "Technologie",
    bio: "Dev full-stack avec 10 ans d'expérience. Travaille actuellement dans une startup tech à Montréal. Alumni de l'Université Quisqueya.",
    languages: ["Français", "Créole", "Anglais"],
    country: "Canada",
    availability: "Soirs (EST)",
    sessions: 92,
    rating: 4.8,
    avatar: "JB",
  },
  {
    id: "m3",
    name: "Me. Sophia Belizaire",
    profession: "Avocate d'Affaires",
    domain: "Juridique",
    bio: "Avocate spécialisée en droit des affaires et droit international. Diplômée de l'UEH et de Paris II Panthéon-Assas. Consultante pour plusieurs entreprises régionales.",
    languages: ["Français", "Créole", "Anglais", "Espagnol"],
    country: "Haïti",
    availability: "Mercredi après-midi",
    sessions: 35,
    rating: 5.0,
    avatar: "SB",
  },
  {
    id: "m4",
    name: "Frantz Estimable",
    profession: "Directeur d'École & Pédagogue",
    domain: "Éducation",
    bio: "25 ans dans l'éducation nationale. Directeur d'un lycée privé à Port-au-Prince. Formateur certifié en pédagogie active et curriculum design.",
    languages: ["Français", "Créole"],
    country: "Haïti",
    availability: "Samedi matin",
    sessions: 67,
    rating: 4.7,
    avatar: "FE",
  },
  {
    id: "m5",
    name: "Nadège Thermilus",
    profession: "Architecte & Urbaniste",
    domain: "Ingénierie",
    bio: "Architecte primée, spécialisée en construction parasismique et logement abordable. Fondatrice d'un cabinet d'architecture social à Haïti.",
    languages: ["Français", "Créole", "Anglais"],
    country: "Haïti",
    availability: "Vendredi soir",
    sessions: 29,
    rating: 4.9,
    avatar: "NT",
  },
  {
    id: "m6",
    name: "Réginald Cajuste",
    profession: "Agronome & Entrepreneur",
    domain: "Agriculture",
    bio: "Fondateur d'une coopérative agricole dans l'Artibonite. Expert en agriculture durable et sécurité alimentaire. Diplômé de la Faculté d'Agronomie de l'UEH.",
    languages: ["Français", "Créole"],
    country: "Haïti",
    availability: "Dimanche",
    sessions: 41,
    rating: 4.6,
    avatar: "RC",
  },
];

export const ROADMAPS: CareerRoadmap[] = [
  {
    careerId: "medecine",
    steps: [
      {
        grade: "3ème",
        actions: [
          "Concentre-toi sur Biologie, Chimie, Physique, Maths",
          "Rejoins un club de sciences à l'école",
          "Lis des articles de vulgarisation médicale",
          "Fais du bénévolat dans un centre de santé communautaire",
        ],
      },
      {
        grade: "2ème",
        actions: [
          "Prépare ton dossier académique (relève de notes)",
          "Participe aux olympiades de sciences",
          "Commence à étudier l'anatomie de base",
          "Rencontre un médecin mentor via Xpoze",
        ],
      },
      {
        grade: "Rhéto",
        actions: [
          "Prépare le concours d'entrée en médecine (UEH)",
          "Étudie les annales des concours précédents",
          "Améliore ton niveau d'anglais (littérature médicale)",
          "Identifie des bourses disponibles",
        ],
      },
      {
        grade: "Philo",
        actions: [
          "Constitue ton dossier complet d'admission",
          "Passe le concours d'entrée en médecine",
          "Prépare une lettre de motivation",
          "Explore des programmes à l'étranger en backup",
        ],
      },
    ],
    documents: [
      "Relevé de notes (4 dernières années)",
      "Acte de naissance",
      "Certificat médical",
      "Photos d'identité",
      "Lettre de motivation",
      "Lettre de recommandation d'un professeur",
    ],
  },
  {
    careerId: "informatique",
    steps: [
      {
        grade: "3ème",
        actions: [
          "Apprends les bases de la programmation (Python, Scratch)",
          "Suis des cours en ligne gratuits (freeCodeCamp, Khan Academy)",
          "Développe ta logique avec les maths et puzzles",
          "Monte ton premier site web simple",
        ],
      },
      {
        grade: "2ème",
        actions: [
          "Apprends HTML/CSS/JavaScript basique",
          "Crée des petits projets personnels",
          "Rejoins des communautés tech locales",
          "Explore les métiers: dev web, data, cybersécurité, IA",
        ],
      },
      {
        grade: "Rhéto",
        actions: [
          "Construis un portfolio de 2-3 projets",
          "Prépare les tests d'entrée universitaires",
          "Certifications gratuites (Google, Meta sur Coursera)",
          "Commence à chercher des stages d'été",
        ],
      },
      {
        grade: "Philo",
        actions: [
          "Finalise ton portfolio GitHub",
          "Postule dans les universités cibles",
          "Prépare des entretiens techniques de base",
          "Networking: LinkedIn, communautés tech haïtiennes",
        ],
      },
    ],
    documents: [
      "Relevé de notes",
      "Portfolio de projets (GitHub ou site web)",
      "Lettre de motivation",
      "CV académique",
      "Lettre de recommandation",
      "Acte de naissance",
    ],
  },
];

export const RIASEC_QUESTIONS = [
  // Realistic
  { id: 1, type: "R", text: "Mwen renmen travay ak zouti ak ekipman." },
  { id: 2, type: "R", text: "Mwen pito fè bagay ak men mwen pase pale sou yo." },
  { id: 3, type: "R", text: "Mwen enterese nan mekanik, elektrisite, oswa jeni." },
  // Investigative
  { id: 4, type: "I", text: "Mwen renmen rezoud pwoblèm konplèks ak syantifik." },
  { id: 5, type: "I", text: "Mwen renmen fè rechèch ak analiz done." },
  { id: 6, type: "I", text: "Mwen enterese nan syans, medsin, oswa teknoloji." },
  // Artistic
  { id: 7, type: "A", text: "Mwen renmen eksprime tèt mwen atravè atizana, mizik, oswa ekri." },
  { id: 8, type: "A", text: "Mwen renmen kreye bagay orijinal ak inovatif." },
  { id: 9, type: "A", text: "Mwen atire pa dizay, fotografi, oswa teyat." },
  // Social
  { id: 10, type: "S", text: "Mwen renmen ede lòt moun ak pwoblèm yo." },
  { id: 11, type: "S", text: "Mwen bon nan kominike ak travay ann ekip." },
  { id: 12, type: "S", text: "Mwen enterese nan ansèyman, swen, oswa travay sosyal." },
  // Enterprising
  { id: 13, type: "E", text: "Mwen renmen dirije ak pran inisyativ nan yon gwoup." },
  { id: 14, type: "E", text: "Mwen enterese nan biznis, vant, oswa jesyon." },
  { id: 15, type: "E", text: "Mwen renmen konvenk lòt moun ak negosye." },
  // Conventional
  { id: 16, type: "C", text: "Mwen renmen organize, klasifye ak jere done." },
  { id: 17, type: "C", text: "Mwen pito travay avèk règ klè ak pwosedi." },
  { id: 18, type: "C", text: "Mwen bon nan kontabilite, administrasyon, ak travay biwo." },
];

// ─── World Universities ───────────────────────────────────────────────────────

export const WORLD_UNIVERSITIES: University[] = [
  {
    id: "mit",
    name: "Massachusetts Institute of Technology (MIT)",
    country: "USA",
    city: "Cambridge, MA",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://mit.edu",
    programs: [],
  },
  {
    id: "harvard",
    name: "Harvard University",
    country: "USA",
    city: "Cambridge, MA",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://harvard.edu",
    programs: [],
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "USA",
    city: "Stanford, CA",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://stanford.edu",
    programs: [],
  },
  {
    id: "oxford",
    name: "University of Oxford",
    country: "Royaume-Uni",
    city: "Oxford",
    type: "Public",
    languages: ["Anglais"],
    website: "https://ox.ac.uk",
    programs: [],
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    country: "Royaume-Uni",
    city: "Cambridge",
    type: "Public",
    languages: ["Anglais"],
    website: "https://cam.ac.uk",
    programs: [],
  },
  {
    id: "eth-zurich",
    name: "ETH Zurich",
    country: "Suisse",
    city: "Zurich",
    type: "Public",
    languages: ["Allemand", "Anglais"],
    website: "https://ethz.ch",
    programs: [],
  },
  {
    id: "mcgill",
    name: "Université McGill",
    country: "Canada",
    city: "Montréal",
    type: "Public",
    languages: ["Anglais", "Français"],
    website: "https://mcgill.ca",
    programs: [],
  },
  {
    id: "utoronto",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    type: "Public",
    languages: ["Anglais"],
    website: "https://utoronto.ca",
    programs: [],
  },
  {
    id: "sorbonne",
    name: "Sorbonne Université",
    country: "France",
    city: "Paris",
    type: "Public",
    languages: ["Français"],
    website: "https://sorbonne-universite.fr",
    programs: [],
  },
  {
    id: "paris-saclay",
    name: "Université Paris-Saclay",
    country: "France",
    city: "Gif-sur-Yvette",
    type: "Public",
    languages: ["Français", "Anglais"],
    website: "https://universite-paris-saclay.fr",
    programs: [],
  },
  {
    id: "hec-paris",
    name: "HEC Paris",
    country: "France",
    city: "Jouy-en-Josas",
    type: "Privé",
    languages: ["Français", "Anglais"],
    website: "https://hec.edu",
    programs: [],
  },
  {
    id: "sciences-po",
    name: "Sciences Po Paris",
    country: "France",
    city: "Paris",
    type: "Public",
    languages: ["Français", "Anglais"],
    website: "https://sciencespo.fr",
    programs: [],
  },
  {
    id: "umontreal",
    name: "Université de Montréal",
    country: "Canada",
    city: "Montréal",
    type: "Public",
    languages: ["Français"],
    website: "https://umontreal.ca",
    programs: [],
  },
  {
    id: "ulaval",
    name: "Université Laval",
    country: "Canada",
    city: "Québec",
    type: "Public",
    languages: ["Français"],
    website: "https://ulaval.ca",
    programs: [],
  },
  {
    id: "univ-antilles",
    name: "Université des Antilles",
    country: "France",
    city: "Pointe-à-Pitre",
    type: "Public",
    languages: ["Français"],
    website: "https://univ-antilles.fr",
    programs: [],
  },
  {
    id: "ucf",
    name: "University of Central Florida (UCF)",
    country: "USA",
    city: "Orlando, FL",
    type: "Public",
    languages: ["Anglais"],
    website: "https://ucf.edu",
    programs: [],
  },
  {
    id: "fiu",
    name: "Florida International University (FIU)",
    country: "USA",
    city: "Miami, FL",
    type: "Public",
    languages: ["Anglais"],
    website: "https://fiu.edu",
    programs: [],
  },
  {
    id: "miami",
    name: "University of Miami",
    country: "USA",
    city: "Coral Gables, FL",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://miami.edu",
    programs: [],
  },
  {
    id: "nyu",
    name: "New York University (NYU)",
    country: "USA",
    city: "New York, NY",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://nyu.edu",
    programs: [],
  },
  {
    id: "howard",
    name: "Howard University",
    country: "USA",
    city: "Washington, DC",
    type: "Privé",
    languages: ["Anglais"],
    website: "https://howard.edu",
    programs: [],
  },
  {
    id: "ucad",
    name: "Université Cheikh Anta Diop (UCAD)",
    country: "Sénégal",
    city: "Dakar",
    type: "Public",
    languages: ["Français"],
    website: "https://ucad.sn",
    programs: [],
  },
  {
    id: "usherbrooke",
    name: "Université de Sherbrooke",
    country: "Canada",
    city: "Sherbrooke",
    type: "Public",
    languages: ["Français"],
    website: "https://usherbrooke.ca",
    programs: [],
  },
];

// ─── World Programs ───────────────────────────────────────────────────────────

export const WORLD_PROGRAMS: Program[] = [
  // MIT
  {
    id: "mit-cs",
    name: "Bachelor of Science in Computer Science",
    nameHT: "Lisans Enfòmatik MIT",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 57986,
    tuitionMax: 57986,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["SAT/ACT", "TOEFL 100+", "Lettre de recommandation", "Portfolio académique"],
    universityId: "mit",
    universityName: "MIT",
    country: "USA",
  },
  {
    id: "mit-eng",
    name: "Master of Engineering",
    nameHT: "Metriz Jeni MIT",
    domain: "Ingénierie",
    duration: "1 an",
    level: "Master",
    language: "Anglais",
    tuitionMin: 57986,
    tuitionMax: 57986,
    currency: "USD/an",
    deadline: "Décembre",
    scholarship: true,
    requirements: ["Licence en ingénierie", "GRE", "TOEFL 100+", "3 lettres de recommandation"],
    universityId: "mit",
    universityName: "MIT",
    country: "USA",
  },
  // Harvard
  {
    id: "harvard-law",
    name: "Juris Doctor (JD)",
    nameHT: "Doktora Dwa Harvard",
    domain: "Juridique",
    duration: "3 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 67081,
    tuitionMax: 67081,
    currency: "USD/an",
    deadline: "Février",
    scholarship: true,
    requirements: ["Licence", "LSAT 170+", "TOEFL", "Lettres de recommandation"],
    universityId: "harvard",
    universityName: "Harvard University",
    country: "USA",
  },
  {
    id: "harvard-med",
    name: "Doctor of Medicine (MD)",
    nameHT: "Doktora Medsin Harvard",
    domain: "Santé",
    duration: "4 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 67000,
    tuitionMax: 67000,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Licence sciences", "MCAT 520+", "TOEFL", "Expérience clinique"],
    universityId: "harvard",
    universityName: "Harvard University",
    country: "USA",
  },
  // Stanford
  {
    id: "stanford-cs",
    name: "BS Computer Science",
    nameHT: "Lisans Enfòmatik Stanford",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 56169,
    tuitionMax: 56169,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["SAT/ACT", "TOEFL 100+", "Portfolio", "Essai personnel"],
    universityId: "stanford",
    universityName: "Stanford University",
    country: "USA",
  },
  {
    id: "stanford-mba",
    name: "MBA (Graduate School of Business)",
    nameHT: "MBA Stanford",
    domain: "Commerce",
    duration: "2 ans",
    level: "Master",
    language: "Anglais",
    tuitionMin: 74706,
    tuitionMax: 74706,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["Licence", "GMAT 730+", "TOEFL", "Expérience professionnelle 3+ ans"],
    universityId: "stanford",
    universityName: "Stanford University",
    country: "USA",
  },
  // Oxford
  {
    id: "oxford-law",
    name: "Bachelor of Civil Law (BCL)",
    nameHT: "Lisans Dwa Oxford",
    domain: "Juridique",
    duration: "1 an",
    level: "Master",
    language: "Anglais",
    tuitionMin: 30000,
    tuitionMax: 32000,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["Licence en droit", "IELTS 7.5+", "2 lettres de recommandation"],
    universityId: "oxford",
    universityName: "University of Oxford",
    country: "Royaume-Uni",
  },
  {
    id: "oxford-cs",
    name: "MSc Computer Science",
    nameHT: "Metriz Enfòmatik Oxford",
    domain: "Technologie",
    duration: "1 an",
    level: "Master",
    language: "Anglais",
    tuitionMin: 29000,
    tuitionMax: 32000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: true,
    requirements: ["Licence informatique", "IELTS 7.5+", "Relevé de notes excellent"],
    universityId: "oxford",
    universityName: "University of Oxford",
    country: "Royaume-Uni",
  },
  // Cambridge
  {
    id: "cambridge-eng",
    name: "MEng Engineering",
    nameHT: "Metriz Jeni Cambridge",
    domain: "Ingénierie",
    duration: "4 ans",
    level: "Master",
    language: "Anglais",
    tuitionMin: 28000,
    tuitionMax: 35000,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["A-Levels / Équivalent", "IELTS 7.5+", "Entretien"],
    universityId: "cambridge",
    universityName: "University of Cambridge",
    country: "Royaume-Uni",
  },
  {
    id: "cambridge-med",
    name: "MB BChir Medicine",
    nameHT: "Doktora Medsin Cambridge",
    domain: "Santé",
    duration: "6 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 28000,
    tuitionMax: 38000,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["A-Levels Sciences", "BMAT", "IELTS 7.5+", "Entretien"],
    universityId: "cambridge",
    universityName: "University of Cambridge",
    country: "Royaume-Uni",
  },
  // ETH Zurich
  {
    id: "eth-cs",
    name: "MSc Computer Science",
    nameHT: "Metriz Enfòmatik ETH Zurich",
    domain: "Technologie",
    duration: "2 ans",
    level: "Master",
    language: "Anglais",
    tuitionMin: 1460,
    tuitionMax: 1460,
    currency: "USD/an",
    deadline: "Décembre",
    scholarship: true,
    requirements: ["Licence informatique", "IELTS/TOEFL", "Relevé de notes"],
    universityId: "eth-zurich",
    universityName: "ETH Zurich",
    country: "Suisse",
  },
  {
    id: "eth-arch",
    name: "MSc Architecture",
    nameHT: "Metriz Achitekti ETH Zurich",
    domain: "Ingénierie",
    duration: "2 ans",
    level: "Master",
    language: "Anglais",
    tuitionMin: 1460,
    tuitionMax: 1460,
    currency: "USD/an",
    deadline: "Décembre",
    scholarship: false,
    requirements: ["Licence architecture", "Portfolio", "IELTS 7+"],
    universityId: "eth-zurich",
    universityName: "ETH Zurich",
    country: "Suisse",
  },
  // McGill
  {
    id: "mcgill-med",
    name: "Doctorat en Médecine (MDCM)",
    nameHT: "Doktora Medsin McGill",
    domain: "Santé",
    duration: "4 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 15000,
    tuitionMax: 25000,
    currency: "USD/an",
    deadline: "Novembre",
    scholarship: true,
    requirements: ["Licence sciences", "MCAT", "TOEFL/IELTS", "Expérience clinique"],
    universityId: "mcgill",
    universityName: "Université McGill",
    country: "Canada",
  },
  {
    id: "mcgill-cs",
    name: "BSc Computer Science",
    nameHT: "Lisans Enfòmatik McGill",
    domain: "Technologie",
    duration: "3 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 14000,
    tuitionMax: 20000,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["DEC / Bac", "TOEFL/IELTS", "Relevé de notes"],
    universityId: "mcgill",
    universityName: "Université McGill",
    country: "Canada",
  },
  // HEC Paris
  {
    id: "hec-mba",
    name: "MBA HEC Paris",
    nameHT: "MBA HEC Paris",
    domain: "Commerce",
    duration: "16 mois",
    level: "Master",
    language: "Anglais",
    tuitionMin: 72000,
    tuitionMax: 72000,
    currency: "USD/total",
    deadline: "Mars",
    scholarship: true,
    requirements: ["Licence", "GMAT 690+", "TOEFL/IELTS", "Expérience professionnelle 3+ ans"],
    universityId: "hec-paris",
    universityName: "HEC Paris",
    country: "France",
  },
  {
    id: "hec-msc",
    name: "MSc Management",
    nameHT: "Metriz Jesyon HEC Paris",
    domain: "Commerce",
    duration: "1 an",
    level: "Master",
    language: "Français",
    tuitionMin: 22000,
    tuitionMax: 22000,
    currency: "USD/an",
    deadline: "Avril",
    scholarship: true,
    requirements: ["Licence gestion/économie", "GMAT/GRE", "TOEFL/TCF", "Entretien"],
    universityId: "hec-paris",
    universityName: "HEC Paris",
    country: "France",
  },
  // Sciences Po
  {
    id: "sciencespo-law",
    name: "Master Droit International",
    nameHT: "Metriz Dwa Entènasyonal Sciences Po",
    domain: "Juridique",
    duration: "2 ans",
    level: "Master",
    language: "Français",
    tuitionMin: 13000,
    tuitionMax: 16000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: true,
    requirements: ["Licence droit", "TCF/DALF C1", "Lettre de motivation", "CV"],
    universityId: "sciences-po",
    universityName: "Sciences Po Paris",
    country: "France",
  },
  {
    id: "sciencespo-comms",
    name: "Master Communication et Médias",
    nameHT: "Metriz Kominikasyon Sciences Po",
    domain: "Médias",
    duration: "2 ans",
    level: "Master",
    language: "Français",
    tuitionMin: 13000,
    tuitionMax: 16000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: true,
    requirements: ["Licence", "TCF B2 minimum", "Dossier de motivation", "CV"],
    universityId: "sciences-po",
    universityName: "Sciences Po Paris",
    country: "France",
  },
  // Université de Montréal
  {
    id: "umontreal-med",
    name: "Doctorat en Médecine (MD)",
    nameHT: "Doktora Medsin Montréal",
    domain: "Santé",
    duration: "4 ans",
    level: "Doctorat",
    language: "Français",
    tuitionMin: 15000,
    tuitionMax: 22000,
    currency: "USD/an",
    deadline: "Novembre",
    scholarship: true,
    requirements: ["DEC sciences", "CASPer test", "Excellent dossier académique"],
    universityId: "umontreal",
    universityName: "Université de Montréal",
    country: "Canada",
  },
  {
    id: "umontreal-droit",
    name: "Baccalauréat en Droit (LL.B.)",
    nameHT: "Lisans Dwa Montréal",
    domain: "Juridique",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 7000,
    tuitionMax: 12000,
    currency: "USD/an",
    deadline: "Février",
    scholarship: true,
    requirements: ["DEC / Équivalent", "TCF B2+", "Dossier scolaire"],
    universityId: "umontreal",
    universityName: "Université de Montréal",
    country: "Canada",
  },
  // Université Laval
  {
    id: "ulaval-agro",
    name: "Baccalauréat en Agronomie",
    nameHT: "Lisans Agwonomi Laval",
    domain: "Agriculture",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 6000,
    tuitionMax: 10000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: true,
    requirements: ["DEC sciences", "TCF B1+", "Relevé de notes"],
    universityId: "ulaval",
    universityName: "Université Laval",
    country: "Canada",
  },
  {
    id: "ulaval-info",
    name: "Baccalauréat en Génie Informatique",
    nameHT: "Lisans Jeni Enfòmatik Laval",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 6000,
    tuitionMax: 10000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: false,
    requirements: ["DEC sciences/techniques", "TCF B1+", "Relevé de notes"],
    universityId: "ulaval",
    universityName: "Université Laval",
    country: "Canada",
  },
  // Université des Antilles
  {
    id: "antilles-info",
    name: "Licence Informatique",
    nameHT: "Lisans Enfòmatik Antilles",
    domain: "Technologie",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 2000,
    tuitionMax: 4000,
    currency: "USD/an",
    deadline: "Juin",
    scholarship: true,
    requirements: ["Bac", "Parcoursup", "Niveau B1 français"],
    universityId: "univ-antilles",
    universityName: "Université des Antilles",
    country: "France",
  },
  // UCF
  {
    id: "ucf-cs",
    name: "BS Computer Science",
    nameHT: "Lisans Enfòmatik UCF",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 22467,
    tuitionMax: 22467,
    currency: "USD/an",
    deadline: "Juillet",
    scholarship: true,
    requirements: ["High School Diploma", "SAT/ACT", "TOEFL 80+", "Relevé de notes"],
    universityId: "ucf",
    universityName: "UCF",
    country: "USA",
  },
  {
    id: "ucf-edu",
    name: "BS Education",
    nameHT: "Lisans Edikasyon UCF",
    domain: "Éducation",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 22467,
    tuitionMax: 22467,
    currency: "USD/an",
    deadline: "Juillet",
    scholarship: true,
    requirements: ["High School Diploma", "TOEFL 80+", "Relevé de notes"],
    universityId: "ucf",
    universityName: "UCF",
    country: "USA",
  },
  // FIU
  {
    id: "fiu-business",
    name: "Bachelor of Business Administration",
    nameHT: "Lisans Adminis Biznis FIU",
    domain: "Commerce",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 18956,
    tuitionMax: 18956,
    currency: "USD/an",
    deadline: "Juillet",
    scholarship: true,
    requirements: ["High School Diploma", "SAT/ACT", "TOEFL 80+"],
    universityId: "fiu",
    universityName: "FIU",
    country: "USA",
  },
  {
    id: "fiu-cs",
    name: "BS Computer Science",
    nameHT: "Lisans Enfòmatik FIU",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 18956,
    tuitionMax: 18956,
    currency: "USD/an",
    deadline: "Juillet",
    scholarship: true,
    requirements: ["High School Diploma", "SAT/ACT", "TOEFL 80+"],
    universityId: "fiu",
    universityName: "FIU",
    country: "USA",
  },
  // NYU
  {
    id: "nyu-law",
    name: "Juris Doctor (JD)",
    nameHT: "Doktora Dwa NYU",
    domain: "Juridique",
    duration: "3 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 68000,
    tuitionMax: 68000,
    currency: "USD/an",
    deadline: "Février",
    scholarship: true,
    requirements: ["Licence", "LSAT 169+", "TOEFL", "Lettres de recommandation"],
    universityId: "nyu",
    universityName: "NYU",
    country: "USA",
  },
  {
    id: "nyu-comms",
    name: "MA Journalism",
    nameHT: "Metriz Jounalis NYU",
    domain: "Médias",
    duration: "1 an",
    level: "Master",
    language: "Anglais",
    tuitionMin: 52000,
    tuitionMax: 52000,
    currency: "USD/an",
    deadline: "Janvier",
    scholarship: true,
    requirements: ["Licence", "TOEFL 100+", "Portfolio journalistique", "Lettre de motivation"],
    universityId: "nyu",
    universityName: "NYU",
    country: "USA",
  },
  // Howard
  {
    id: "howard-med",
    name: "Doctor of Medicine (MD)",
    nameHT: "Doktora Medsin Howard",
    domain: "Santé",
    duration: "4 ans",
    level: "Doctorat",
    language: "Anglais",
    tuitionMin: 40000,
    tuitionMax: 45000,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Licence sciences", "MCAT", "TOEFL", "Expérience clinique"],
    universityId: "howard",
    universityName: "Howard University",
    country: "USA",
  },
  {
    id: "howard-cs",
    name: "BS Computer Science",
    nameHT: "Lisans Enfòmatik Howard",
    domain: "Technologie",
    duration: "4 ans",
    level: "Licence",
    language: "Anglais",
    tuitionMin: 28000,
    tuitionMax: 28000,
    currency: "USD/an",
    deadline: "Novembre",
    scholarship: true,
    requirements: ["High School Diploma", "SAT/ACT", "TOEFL 80+"],
    universityId: "howard",
    universityName: "Howard University",
    country: "USA",
  },
  // UCAD
  {
    id: "ucad-droit",
    name: "Licence en Droit",
    nameHT: "Lisans Dwa Dakar",
    domain: "Juridique",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 500,
    tuitionMax: 1500,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Bac", "Dossier scolaire"],
    universityId: "ucad",
    universityName: "Université Cheikh Anta Diop",
    country: "Sénégal",
  },
  {
    id: "ucad-med",
    name: "Doctorat en Médecine",
    nameHT: "Doktora Medsin Dakar",
    domain: "Santé",
    duration: "7 ans",
    level: "Doctorat",
    language: "Français",
    tuitionMin: 500,
    tuitionMax: 2000,
    currency: "USD/an",
    deadline: "Octobre",
    scholarship: true,
    requirements: ["Bac scientifique", "Concours d'entrée", "Dossier médical"],
    universityId: "ucad",
    universityName: "Université Cheikh Anta Diop",
    country: "Sénégal",
  },
  // Université de Sherbrooke
  {
    id: "usherbrooke-info",
    name: "Baccalauréat en Informatique",
    nameHT: "Lisans Enfòmatik Sherbrooke",
    domain: "Technologie",
    duration: "3 ans",
    level: "Licence",
    language: "Français",
    tuitionMin: 7000,
    tuitionMax: 11000,
    currency: "USD/an",
    deadline: "Mars",
    scholarship: false,
    requirements: ["DEC", "TCF B1+", "Relevé de notes"],
    universityId: "usherbrooke",
    universityName: "Université de Sherbrooke",
    country: "Canada",
  },
  {
    id: "usherbrooke-gestion",
    name: "MBA — École de Gestion",
    nameHT: "MBA Sherbrooke",
    domain: "Commerce",
    duration: "2 ans",
    level: "Master",
    language: "Français",
    tuitionMin: 12000,
    tuitionMax: 18000,
    currency: "USD/an",
    deadline: "Avril",
    scholarship: true,
    requirements: ["Licence", "GMAT/GRE", "TCF B2+", "Expérience professionnelle"],
    universityId: "usherbrooke",
    universityName: "Université de Sherbrooke",
    country: "Canada",
  },
];

// ─── Career Salary Data ───────────────────────────────────────────────────────

export const CAREER_SALARIES: Record<string, { level: string; min: number; max: number }[]> = {
  medecine: [
    { level: "Interne (1-3 ans)", min: 30000, max: 50000 },
    { level: "Résident (3-6 ans)", min: 50000, max: 80000 },
    { level: "Médecin généraliste", min: 80000, max: 150000 },
    { level: "Spécialiste", min: 150000, max: 350000 },
  ],
  informatique: [
    { level: "Junior (0-2 ans)", min: 45000, max: 75000 },
    { level: "Mid-level (2-5 ans)", min: 75000, max: 120000 },
    { level: "Senior (5-10 ans)", min: 120000, max: 180000 },
    { level: "Lead / Architecte", min: 180000, max: 300000 },
  ],
  gestion: [
    { level: "Analyste / Assistant", min: 35000, max: 55000 },
    { level: "Manager", min: 55000, max: 90000 },
    { level: "Directeur", min: 90000, max: 150000 },
    { level: "VP / C-Suite", min: 150000, max: 400000 },
  ],
  droit: [
    { level: "Stagiaire / Clerc", min: 25000, max: 50000 },
    { level: "Avocat junior", min: 60000, max: 100000 },
    { level: "Avocat confirmé", min: 100000, max: 180000 },
    { level: "Associé / Juge", min: 180000, max: 350000 },
  ],
  architecture: [
    { level: "Architecte junior", min: 40000, max: 65000 },
    { level: "Architecte (5 ans)", min: 65000, max: 100000 },
    { level: "Architecte senior", min: 100000, max: 150000 },
    { level: "Associé / Fondateur", min: 150000, max: 280000 },
  ],
  education: [
    { level: "Enseignant débutant", min: 25000, max: 45000 },
    { level: "Enseignant confirmé", min: 45000, max: 65000 },
    { level: "Directeur d'école", min: 60000, max: 90000 },
    { level: "Inspecteur / Consultant", min: 80000, max: 130000 },
  ],
  agronomie: [
    { level: "Technicien agricole", min: 25000, max: 40000 },
    { level: "Agronome junior", min: 40000, max: 65000 },
    { level: "Agronome senior", min: 65000, max: 100000 },
    { level: "Directeur / Consultant", min: 100000, max: 180000 },
  ],
  communication: [
    { level: "Journaliste / Stagiaire", min: 25000, max: 45000 },
    { level: "Rédacteur confirmé", min: 45000, max: 70000 },
    { level: "Chef de rubrique / PR", min: 70000, max: 110000 },
    { level: "Directeur de communication", min: 110000, max: 200000 },
  ],
};

export function getCareersByRiasec(codes: string[]): Career[] {
  return CAREERS.filter((c) =>
    c.riasecCodes.some((code) => codes.includes(code))
  ).sort((a, b) => {
    const aScore = a.riasecCodes.filter((c) => codes.includes(c)).length;
    const bScore = b.riasecCodes.filter((c) => codes.includes(c)).length;
    return bScore - aScore;
  });
}
